Fixed and tested changes, adding and removing
clalancette/old-cmd_vel_mux pull request #5
Opened 2020-02-12 12:55 UTC by Lobotuerk

Fixed @hidmic comments, fixed changing, adding and removing. TODO: change the used_priorities_ to local instead of global as Mich wanted to, just want to PR the working version first

2020-02-12 13:27 UTC, hidmic requested changes

2020-02-12 13:27 UTC, hidmic commented on src/cmd_vel_mux.cpp
> +    if (parameter.second.timeout < 0.0)
@Lobotuerk you may remove all `else` clauses here.

2020-02-12 13:27 UTC, hidmic commented on src/cmd_vel_mux.cpp
> +    const std::string &key = parameter.first;
@Lobotuerk nit:

```suggestion
    const std::string & key = parameter.first;
```

Same elsewhere.

2020-02-12 13:27 UTC, hidmic commented on src/cmd_vel_mux.cpp
> +    const std::string &key = m.first;
@Lobotuerk nit: consider doing the same aliasing for `m.second`.

2020-02-12 13:27 UTC, hidmic commented on src/cmd_vel_mux.cpp
> +    }
@Lobotuerk `addInputToParameterMap` should not have an effect on the current state. Only `configureParameters` can carry out this operation.

2020-02-12 15:27 UTC, Lobotuerk commented
@hidmic

2020-02-13 14:03 UTC, hidmic approved these changes
Way to go man, LGTM!

2020-02-13 17:24 UTC, clalancette approved these changes
Looks good!  I'm going to merge this into my PR, but I won't merge the whole thing to master until next week.  Thanks @Lobotuerk !

2020-02-13 17:25 UTC, merged